services:
  db:
    image: postgres:16
    container_name: fintrack-db
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U fintrack -d fintrack"]
      interval: 5s
      timeout: 3s
      retries: 10
